### PR TITLE
Better Stata parsing

### PR DESCRIPTION
**Pull request by rbisewski**
Since our new code guideline recommend `do`/`run` rather than `include`, I have since adjusted the SAS code and regex to allow for this to be handled properly, and expanded the Stata demo tests and changelog.

During on-RAS testing there was initially a problem with unusual errors occurring. Specifically the issue was two-fold; older versions of code-diary executing alongside and embedded auto-exec do calls in Stata like:

```
global F8 "do "P:\commond\source\main.do""
```

I have since added checks for these to prevent eternal loops from these embedded calls and to only run the first version of code-diary called. This seems to resolve those issues and allow the new Stata imports to be parsed.

Feel free to run your own tests, and let me know what you think.

### CODE REVIEW

**Comment by rbisewski** [comment]
You bring up a number of helpful points, which hopefully I can address below:

Regarding the script numbering, it seems that the `where` call in the datastep was removing the unnecessary lines, and numbering only from the lines remaining, whereas my code had removed that and been merely skipping them via `if`. A simple solution is to add another datastep to remove the entries we are uninterested in from the start. I think this method this also makes those steps more readable and debuggable for future developers.

Regarding the regex and multiple versions of code-diary, I have since worked with the team to exactly reproduce the issue. Seems to be related to how SAS handles newlines. With some tweaking to the regex, it is now more obvious what it searches for:

```
%let prx_grab_stata_file = 's/^\s*(include|run|do)"?[ \t]+(.+\.do).*"?.*/$2/';
```

Regarding the function keymapping, it seems the old regex was getting confused due to the similarity of the `do` call and the way we handle imports now; e.g. using `do` and `run`. A lazy solution was to just check for the first letter `(i|r|d)`, however, since my conversation with the team, it seems we can just check for the start of a newline, a la `^`, since in Stata that is the only scenario that can occur.

Finally, I have since added a test-case of the keymapping to the demo code in this repo so we can always be aware of this in the future.

Let me know what you think.

**Comment by Righolt** [comment]
I will test when I'm in the office, just a quick Q:
Are you saying that nothing can be entered before the run/do statement on the line (except spaces/tabs) when actually running it (except when setting other chars as command ends in Stata)? How does this work when the file is commented out to speed up runtime (yet you still want the comments from it)?

**Comment by rbisewski** [comment]
Ah, I see. So we want to be parse comments read from Stata code lines that are commented out?

If that's the case, I think a simple tweak to the regex need only take into account [these](https://www.stata.com/help.cgi?comments) mentioned comment types? So perhaps something like this then:

```
%let prx_grab_stata_file = 's/^[\s\/*]*(include|run|do)"?[ \t]+(.+\.do).*"?.*/$2/';
```

The line may also start with one-or-more of a `/` or `*` character (for commented code) or a whitespace (for uncommented code). Does this work for you?

**Comment by Righolt** [comment]
I think that are all the comment styles yes.

**Comment by rbisewski** [comment]
The adjusted regex has since been merged to branch; the annoying merge is due to regen'd output, which is at line 5 since the new test was added, as expected. It appears to work on-and-off RAS, for both me and Gurpret.

Feel free to run your own tests to ensure it works as we expect, whenever you have time.

**Comment by rbisewski** [comment]
I can add a comment to the Stata regex, if you think it warrants. Regarding the `"`, that is for scenarios involving embedded calls of Stata files with multiple `"` characters inside of each other like so:

```
 global F8 "do "P:\commond\source\main.do""
```

The regex usually captures something like:

```
"P:\commond\source\main.do
```

I suppose I could have added another set of `"?` yet I think in this scenario that would make a regex a bit murkier. I figured perhaps a `compress` call would be easier to read.

Also note that the first set of `"` in the regex are just to check for normal file importing, which is like this:

```
do "`SOURCE_ROOT'/macros/general/get_base_variable_name.do"
```

So I can remove the `compress` call if you like. You thoughts?

**Comment by Righolt** [comment]
The regex is already hard to crack, so either do it all in one step or break it up in more manageable portions, singling out the " does not make things clearer in my mind.

**Comment by rbisewski** [comment]
As per our discussion, I have since made the requested changes. I think [this](https://github.com/VaccineAndDrugEvaluationCentre/code-diary-sas/blob/4befa705f1e6ad6ab1640f47bd8b972ffec6390c/source/code_diary.sas#L855) is more straightforward. Let me know if the current state of the function looks readable.

Gurpret and I have confirmed that it is working both on and off RAS, but feel free to test it again. Once you are satisfied, merge the pull request.

**Pull request merged**
