### PR TITLE
Adjusting code to better fit certain comment use cases

### PR DESCRIPTION
**Pull request by rbisewski**
@Righolt 

As per issue #8 , I have since created a fix that ought to allow that use case and a number of others; most notably certain at-symbol-comments.

Feel free to run some tests on it, and then merge to trunk once you are done.

### CODE REVIEW

**Comment by Righolt** [comment]
@rbisewski It now captures some of the regex's and other items in the parsed output, see [output-coder.md](https://github.com/VaccineAndDrugEvaluationCentre/code-diary-sas/blob/improve_comment_handling/demo/output-coder.md).

**Comment by rbisewski** [comment]
Certain kinds of comments require a lot of logic to make them functional, so I'll have to test it further to ensure it is working.

Anyway, thanks for conducting a test run on my branch. I'll start on creating a fix for that.

**Comment by rbisewski** [comment]
I've created a workaround for the cases where SAS attempts to read regex lines, since escaping * chars with slashes tends to confuse it, hence the bad output you mentioned.

Feel free to give this another test, whenever you have time.

**Comment by rbisewski** [comment]
I have since restored regex functionality and tilda / blank lines are no longer included in the comment output.

In addition, I have added debug output which will hopefully make it easier to determine what 'call execute' statements are actually doing.

Feel free to test this whenever you have time.

**Pull request merged**
